config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  post '/products', to: 'products#create'

  resources :products, only: [:index,:create,:destroy,:show] do
    resources :orders, only: :create
  end

  resources :orders, only: :index do
  	collection do
  		get 'clean'
  	end
  end

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end


#  devise_for :users

  root 'products#index'
  
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
    
       if user.email == "tulio@desafio.com"
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :users, through: :orders
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         
  has_many :orders
  has_many :billings
  has_many :products, through: :orders

  enum role:[:admin,:visit]

# app/models/user.rb


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_url, alert: exception.message }
    end
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
  end
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
    before_action :authenticate_user!
    def index
        @billings = current_user.billings
    end
    def pre_pay
        orders = current_user.orders.where(payed: false)
        total = orders.pluck("price * quantity").sum()
        items = orders.map do |order|
            item = {}
            item[:name] = order.product.name
            item[:sku] = order.id.to_s
            item[:price] = order.price.to_s
            item[:currency] = 'USD'
            item[:quantity] = order.quantity
            item
        end
        
        if Rails.env.development?
            redirect_urls_ok = {
                return_url: "http://localhost:3000/billings/execute",
                cancel_url: "http://localhost:3000/"  
            }
        else
            redirect_urls_ok = {
                return_url: "https://esundetalle.herokuapp.com/billings/execute",
                cancel_url: "https://esundetalle.herokuapp.com/" 
            }
        end
        
        payment = PayPal::SDK::REST::Payment.new({
            intent: "sale",
            payer: {payment_method: "paypal" },
            redirect_urls: redirect_urls_ok,
            transactions: [{
                item_list: {items: items },
                amount: {total: total.to_s, currency: "USD" },
                description: "Compra desde E-commerce Rails." 
            }]
        })

        if payment.create
            redirect_url = payment.links.find{|v| v.method == "REDIRECT"}.href
            redirect_to redirect_url
        else
            render json: payment.error
        end
    end

    def execute
        paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
        if paypal_payment.execute(payer_id: params[:PayerID])
            amount = paypal_payment.transactions.first.amount.total
            billing = Billing.create(
                user: current_user,
                code: paypal_payment.id,
                payment_method: 'paypal',
                amount: amount,
                currency: 'USD'
            )
            orders = current_user.orders.where(payed: false)
            orders.update_all(payed: true, billing_id: billing.id)
            redirect_to root_path, notice: "La compra se realizó con éxito!"
        else
            render plain: "No se puedo generar el cobro en PayPal."
        end
    end
end
        

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def create
    p = Product.find(params[:product_id])
    o = Order.find_or_create_by(user: current_user, product: p, payed: false, price: p.price)
    o.quantity += 1

    if o.save
      redirect_to products_path, notice: "El producto ha sido agregado al carro."
    else
      redirect_to products_path, alert: "El producto NO ha sido agregado al carro"
    end
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = current_user.orders.where(payed: false)
    @total = @orders.pluck("price * quantity").sum()
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  def index
    @products = Product.all
    @product = Product.new
  end


  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def show
    @product = Product.find(params[:id])
  end




  def create
    
    @product = Product.new(product_params)
    
    #@product.images.attach(params[:product][:images])

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      # params.require(:product).permit(:name, :price, :image )
      params.require(:product).permit(:name, :price, images: [])
    end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
            sign_in_and_redirect @user
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
        else
            redirect_to root_path, notice: 'Error al iniciar sesión con Facebook.'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.haml
= semantic_form_for [:admin, @product], builder: ActiveAdmin::FormBuilder do |f|
  = f.inputs do
    = f.input :name
    = f.input :images, as: :file, :input_html => { :multiple => true }
    = f.actions

app/views/billings/index.html.erb
<div class="container">
    <% @billings.each do |billing| %>
       
        <% billing.orders.each do |order| %>
            <p><%= order.product.name%></p>
            <p><%= order.product.price%></p>
            <p><%= order.quantity%></p>
            
        <% end %>    

        <p><%= billing.amount %></p>
        <hr>

    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <br>
    <%= render 'shared/navbar'%>
    <%= render 'shared/header'%>
  <div class="container">
   
    
  
    
   

    <% if alert.present? %>
      <div class="alert alert-warning" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>


    <div class="main-content">
      <%= yield %>
    </div>
    
   



</div>
<%= render 'shared/footer2'%>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/orders/_order.html.erb
<table>
        <tr id='row_<%= order.id %>'>
                <td id = "product_<%=order.product.id%>" > <%= order.product.name %> </td>
                <td> <%= order.product.price %> </td>
                <td> <%= order.quantity %> </td>   
        </tr>
</table>

app/views/orders/create.js.erb
$('#chartheader').html('Ultimos productos agregados')
$('#chartheader').append('<%= j render @orders %>')


 
  

app/views/orders/destroy.js.erb
$('#order_<%=@order.id%>').toggle(1000)

app/views/orders/index.html.erb
<div class="container">



  <% if @orders.count > 0 %>
    <table class="table">
    <thead>
      <tr>
        <th>Producto</th>
        <th>Imagen</th>
        <th>Valor</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
        <th>Quitar</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr id = 'order_<%= order.id %>'>
          <td> <%= order.product.name %> </td>
          <td> <%= image_tag order.product.images[0].variant(resize: '100x100') %> </td>
          <td> <%= order.price %></td>
          <td> <%= order.quantity %> </td>
          <td> <%= order.price * order.quantity %></td>
          <td> 
            <%= link_to order, class: 'delete_order', method: :delete, data: {remote: true} do %>
           <i class="far fa-trash-alt fa-2x"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr class="table-green">
      <td></td>
      <td></td>
      <td></td>   
      <td><strong>Total de la compra:</strong></td>
      <td><strong><%= @total %></strong></td>
      <td></td>   
      </tr>
    </tbody>
  </table>



  <%= link_to 'Limpiar carro', clean_orders_path, class: 'btn btn-danger'  %>

  <%= link_to 'Confirmar compra', pre_pay_billings_path, class: 'btn btn-success float-right' %>
  


  <% else %>
    <p>No tienes productos en tu carro de compra.</p>
  <% end %>

</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" >
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% if can?(:destroy , product) %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

<div class="field">
<%= form.label :images %>
<%= form.file_field :images, multiple: true %>
</div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<% end %>

app/views/products/index.html.erb
  <%= render 'shared/jumbotron'%>




<div class="chart" id='chart'>


</div>
<%= render 'form', product: @product %>
  <div class="row">
    <% @products.each_slice(4) do |row| %>
      <% row.each do |product| %>
        <div class="col">
          <div class="card">
            <% if product.images.attached? %>
              <p>
              <strong>Image:</strong>
              <br>
              <%# (0..(product.images.count-1)).each do |image|%>
                <%= image_tag (product.images[0].variant(resize: "300x300")), class: 'card-img-top' %>
              <%# end %>
              </p>
            <% end %>
    
            <div class="card-body">
              <h5> <%= product.name %> </h5>
              <p> <%= product.price %> </p>
              <%= link_to "Agregar al carro", product_orders_path(product), class: 'btn btn-success', method: :post, data: {remote: :true}  %>
              <% if can?(:destroy , product) %>
                <%= link_to "Borrar producto", product_path(product), class: 'btn btn-danger', method: :delete  %>
              <%end%>
              <%= link_to "detalle producto", product_path(product), class: 'btn btn-primary' %>
              
            </div>
          </div>
        </div>
      <% end %>
      <div class="w-100" style="margin-top:20px;"> </div>
    <% end %>

  </div>

app/views/products/show.html.erb
<div class="row">
    <div class="bd-example col-xl-5">
        <div class="carousel-outer">
                <%= image_tag @product.images.first, :class => "d-block w-100" %>
        </div>
    </div>


    <div class="bd-example col-xl-3">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel"> 
        <% if @product.images.attached?%>
            <% (0..(@product.images.count-1)).each do |i| %>
                <ol class="carousel-indicators">
                <% if i==0%>
                    <li data-target="#carouselExampleCaptions" data-slide-to=i class="active"></li>
                <% else%>    
                    <li data-target="#carouselExampleCaptions" data-slide-to=i></li>
                <% end %>  
                </ol>
            <% end %>
        <% end %>

        <% if @product.images.attached?%>
            <div class="carousel-inner">
                <% @product.images.each do |image|%>
                    <% if image == @product.images.first %>
                    <div class="carousel-item active">
                        <%= image_tag image, :class => "d-block w-100" %>
                        <div class="carousel-caption d-none d-md-block">
                        <h5>First slide label</h5>
                        <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
                        </div>
                    </div>
                    <% else%>   
                        <div class="carousel-item">
                        <%= image_tag image, :class => "d-block w-100" %>
                        <div class="carousel-caption d-none d-md-block">
                        <h5>Second slide label</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <% end %>
                <% end %>
            </div>
        <% end %>

            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="desc">
            <p> 
            Descripción de producto 1
            </p>
        </div>
    </div>


   

 <div class="bd-example col-xl-4">
              <h5> <%= @product.name %> </h5>
              <p> <%= @product.price %> </p>
              <%= link_to "Agregar al carro", product_orders_path(@product), class: 'btn btn-success', method: :post  %>
</div>




</div>

app/views/products/showx.html.haml
.bd-carrusel
  #carouselExampleCaptions.carousel.slide{"data-ride" => "carousel"}
    -if (@product.images.attached?)
      %ol.carousel-indicators
        -(0..1).each do |i|
          -if i == 0
            %li.active{"data-slide-to" => i, "data-target" => "#carouselExampleCaptions"}
          -else
            %li{"data-slide-to" => i, "data-target" => "#carouselExampleCaptions"}
      .carousel-inner
        -@product.images.each_with_index do |image,i|
          -if (i==0)
            .carousel-item.active
            =image_tag image, :class => "d-block.w-100"
          -else
            .carousel-item
            =image_tag image, :class => "d-block.w-100"
              

app/views/shared/_carousel.html.erb
<ol class="carousel-indicators">
   <% @patient.images.each_with_index do |photo, n| %>
     <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
   <% end %>
</ol>

<div class="carousel-inner" role="listbox">
  <div class="item active">
    <%= image_tag @patient.images.first.images_uno.png %>
  </div>
  <% @patient.images.drop(1).each do |photo| %>
     <div class="item">
       <%= image_tag photo.image_file.url %>
     </div>
  <% end %>
</div>

app/views/shared/_footer.html.haml
%blockquote.blockquote.text-center
  %p.mb-0 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.
  %footer.blockquote-footer
    Someone famous in
    %cite{:title => "Source Title"} Source Title

app/views/shared/_footer2.html.erb
<footer class="footer">
<div class="container bottom_border">
<div class="row">
<div class=" col-sm-4 col-md col-sm-4  col-12 col">
<h5 class="headin5_amrc col_white_amrc pt2">Find us</h5>
<!--headin5_amrc-->
<p class="mb10">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
<p><i class="fa fa-location-arrow"></i> 9878/25 sec 9 rohini 35 </p>
<p><i class="fa fa-phone"></i>  +91-9999878398  </p>
<p><i class="fa fa fa-envelope"></i> info@example.com  </p>


</div>


<div class=" col-sm-4 col-md  col-6 col">
<h5 class="headin5_amrc col_white_amrc pt2">Quick links</h5>
<!--headin5_amrc-->
<ul class="footer_ul_amrc">
<li><a href="http://webenlance.com">Image Rectoucing</a></li>
<li><a href="http://webenlance.com">Clipping Path</a></li>
<li><a href="http://webenlance.com">Hollow Man Montage</a></li>
<li><a href="http://webenlance.com">Ebay & Amazon</a></li>
<li><a href="http://webenlance.com">Hair Masking/Clipping</a></li>
<li><a href="http://webenlance.com">Image Cropping</a></li>
</ul>
<!--footer_ul_amrc ends here-->
</div>


<div class=" col-sm-4 col-md  col-6 col">
<h5 class="headin5_amrc col_white_amrc pt2">Quick links</h5>
<!--headin5_amrc-->
<ul class="footer_ul_amrc">
<li><a href="http://webenlance.com">Remove Background</a></li>
<li><a href="http://webenlance.com">Shadows & Mirror Reflection</a></li>
<li><a href="http://webenlance.com">Logo Design</a></li>
<li><a href="http://webenlance.com">Vectorization</a></li>
<li><a href="http://webenlance.com">Hair Masking/Clipping</a></li>
<li><a href="http://webenlance.com">Image Cropping</a></li>
</ul>
<!--footer_ul_amrc ends here-->
</div>


<div class=" col-sm-4 col-md  col-12 col">
<h5 class="headin5_amrc col_white_amrc pt2">Follow us</h5>
<!--headin5_amrc ends here-->

<ul class="footer_ul2_amrc">
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a></p></li>
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a></p></li>
<li><a href="#"><i class="fab fa-twitter fleft padding-right"></i> </a><p>Lorem Ipsum is simply dummy text of the printing...<a href="#">https://www.lipsum.com/</a></p></li>
</ul>
<!--footer_ul2_amrc ends here-->
</div>
</div>
</div>


<div class="container">
<ul class="foote_bottom_ul_amrc">
<li><a href="http://webenlance.com">Home</a></li>
<li><a href="http://webenlance.com">About</a></li>
<li><a href="http://webenlance.com">Services</a></li>
<li><a href="http://webenlance.com">Pricing</a></li>
<li><a href="http://webenlance.com">Blog</a></li>
<li><a href="http://webenlance.com">Contact</a></li>
</ul>
<!--foote_bottom_ul_amrc ends here-->
<p class="text-center">Copyright @2017 | Designed With by <a href="#">Your Company Name</a></p>

<ul class="social_footer_ul">
<li><a href="http://webenlance.com"><i class="fab fa-facebook-f"></i></a></li>
<li><a href="http://webenlance.com"><i class="fab fa-twitter"></i></a></li>
<li><a href="http://webenlance.com"><i class="fab fa-linkedin"></i></a></li>
<li><a href="http://webenlance.com"><i class="fab fa-instagram"></i></a></li>
</ul>
<!--social_footer_ul ends here-->
</div>

</footer>

app/views/shared/_header.html.haml
.card.mb-3
  .row.no-gutters
    .col-md-2
      %img.card-img{:alt => "...", :src => "/compras.png", style: "max-width: 140px;width: 100%;height: 100%;"}
    .col-md-7
      .card-body
        %h5.card-title Es el Mejor E-Commerce
        %p.card-text Disfruta de los mejores articulos.
        %p.card-text
        /=  %small.text-muted Horarios de despacho
        - if notice.present?
          .alert.alert-success{:role => "alert"}
            = notice
        - if alert.present?
          .alert.alert-warning{:role => "alert"}
          = alert    
    #chartheader.col-md-3
     

app/views/shared/_jumbotron.html.haml
.jumbotron.jumbotron-fluid.text-center.bgJumbo 
  .container
    %h1.display-4
    %p.lead 

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary.sticky-top
  %a.navbar-brand{href: root_path} Home
  %button.navbar-toggler{type: "button",
  "data-toggle": "collapse",
  "data-target" => "#navbarSupportedContent",
  "aria-controls" => "navbarSupportedContent",
  "aria-expanded" => "false",
  "aria-label" => "Toggle navigation"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => orders_path } 
          Mi carro
          %span.sr-only (current)
    %ul.navbar-nav.ml-auto
      -if !user_signed_in?
        %li.nav-item
          =link_to 'Sign in', new_user_session_path, class: 'nav-link'
        %li.nav-item
          =link_to 'Sign Up',  new_user_registration_path, class: 'nav-link'
      -else
        %li.nav-item
          %a.nav-link= current_user.email
        %li.nav-item
          = link_to 'Cerrar', destroy_user_session_path, method: :delete, class: 'nav-link'

app/views/shared/_navbar2.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-success sticky-top">
      <a class="navbar-brand" href="<%= root_path %>">Rails-Commerce</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= orders_path %>">Mi carro <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          
            <% if !user_signed_in? %>
              <li class="nav-item">
              <%= link_to 'sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
              <%= link_to 'Sign Up',  new_user_registration_path, class: 'nav-link'%>
              </li>
            <% else %>
            <li class="nav-item">
              <a class="nav-link"><%= current_user.name %></a>
            </li>
            <li class="nav-item">
              <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            <% end %>
            </li>
            
        </ul>
      </div>
    </nav>